[tool.poetry]
name = "coursew-3"
version = "0.1.0"
description = ""
authors = ["Polyakushechka <p20090@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
